version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      ssh: 
      - default=${HOME}/.ssh/id_ed25519chaosweb
    ports:
      - "5173:5000"
    env_file:
      - .env
    volumes:
      - ~/.aws:/root/.aws:ro
      - ~/.ssh/id_ed25519chaosweb:/root/.ssh/id_git_rsa:ro
